Load_on_start:
  - 'zone1'
Leaderboards:
  enabled: false
  type: mysql
  redis_db_info:
    host: 'localhost'
    port: 6379
  mysql_db_info:
    host: 'localhost'
    name: 'minecraft'
    port: 3306
    user: 'user'
    password: 'password'
Region_Provider_Plugin: WorldGuard
External_Economy_Link:
  enabled: false
  external_to_internal:
    allow: true
    # internal = external * rate
    rate: 1
  internal_to_external:
    allow: false
    # external = internal * rate
    rate: 0.5
Zones:
  zone1:
    max_number_of_players: 10
    world: 'world'
    mob_check_task_interval: 60
    soft_mob_respawn: false
    clear_drops: true
    clear_mob_xp: false
    keep_xp_on_respawn: true
    one_time_use_keys: false
    keep_money_on_death: false
    entrance:
      x: 0
      y: 0
      z: 0
      yaw: 0
      pitch: 0
    lobby:
      x: 0
      y: 0
      z: 0
      yaw: 0
      pitch: 0
    starting_money: 35
    kits:
      player:
      - 'LEATHER_HELMET-1'
      - 'LEATHER_CHESTPLATE-1'
      - 'LEATHER_LEGGINGS-1'
      - 'LEATHER_BOOTS-1'
      - 'STONE_SWORD-1'
      - 'BREAD-3'

      donator:
      - 'IRON_HELMET-1'
      - 'IRON_CHESTPLATE-1'
      - 'IRON_LEGGINGS-1'
      - 'IRON_BOOTS-1'
      - 'IRON_SWORD-1|sharpness-1'
      - 'COOKED_BEEF-3'

      admin:
      - 'DIAMOND_HELMET-1|protection-2'
      - 'DIAMOND_CHESTPLATE-1|protection-2'
      - 'DIAMOND_LEGGINGS-1|protection-2'
      - 'DIAMOND_BOOTS-1|protection-2'
      - 'DIAMOND_SWORD-1|sharpness-3|unbreaking-2'
      - 'GOLDEN_APPLE-3'

    money_rewards:
      - 'Zombie:10-15-5'
      - 'Skeleton:15-20-6'
      - 'Spider:15-18-6'
    sub_zones:
      subzone1:
        number_of_mobs: 10
        mob_types:
          - 'Zombie'
          - 'Spider'
          - 'Skeleton'
      subzone2:
        number_of_mobs: 10
        mob_types:
          - 'Zombie'
          - 'Spider'
      subzone3:
        number_of_mobs: 10
        mob_types:
          - 'Zombie'
          - 'Skeleton'
